frase = '   Paulo Sérgio Alves Lopes Filho'
print(frase[5:15])
print(frase[:15])
print(frase[15:])
print(frase[5:15:2])
print(frase[::3])
print(frase[::-1])
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(len(frase))
print(frase.strip())
print(frase.split())
print('-'.join(frase))
dividido=frase.split()
print('-'.join(dividido))
print(frase.replace('Filho', 'Lopes'))
print(frase)
frase=frase.replace('Filho', 'Lopes')
print(frase)
print(frase.count('o',0,30))
print(frase.find('Alves'))
print(frase.lower().find('alves'))
print(frase.find('Julia'))
print(dividido[0])
